version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ubi-wallet-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-wallet_db}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-wallet_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # UBI Wallet Backend Service
  wallet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubi-wallet-backend
    restart: unless-stopped
    ports:
      - "3018:3018"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3018
      - WALLET_PROVIDER=${WALLET_PROVIDER:-dhiway}
      - DHIWAY_API_BASE=${DHIWAY_API_BASE}
      - DHIWAY_API_KEY=${DHIWAY_API_KEY}
      - DHIWAY_VC_ISSUER_INSTANCE_URI=${DHIWAY_VC_ISSUER_INSTANCE_URI}
      - DHIWAY_WATCHER_EMAIL=${DHIWAY_WATCHER_EMAIL}
      - WALLET_SERVICE_BASE_URL=${WALLET_SERVICE_BASE_URL}
      - DHIWAY_VC_ISSUER_GET_VC_BASE_URI=${DHIWAY_VC_ISSUER_GET_VC_BASE_URI}

      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_DATABASE=${DB_DATABASE:-wallet_db}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: