name: Deploy to UBA-DEV

on:
  push:
    branches:
      - '*'  # Trigger on any branch push

jobs:
  Deploy_on_UBA_DEV:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: UBA-DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Deploy Stack via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }} <<'ENDSSH'
          echo "🚀 Starting deployment..."

          # ----- Environment variables -----
          export BASE_DIR="${{ secrets.TARGET_DIR }}"
          export REPO_NAME="ubi-wallet-backend"
          export REPO_URL="https://github.com/PSMRI/ubi-wallet-backend.git"
          export SERVICE_NAME="ubi-wallet-backend"
          export CONTAINER_NAME="ubi-wallet-backend"
          export TAG="latest"
          
          # Determine branch dynamically from push event
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Deploying branch: $BRANCH"

          # ----- Change to base directory -----
          cd "$BASE_DIR" || exit 1

          # ----- Prepare .env -----
          if [ -f .env ]; then rm .env; fi
          echo '${{ secrets.ENV }}' > .env

          # ----- Ensure deploy.sh is executable -----
          chmod +x deploy.sh

          # ----- Run deploy.sh with environment variables -----
          BRANCH="$BRANCH" SERVICE_NAME="$SERVICE_NAME" TAG="$TAG" REPO_NAME="$REPO_NAME" REPO_URL="$REPO_URL" CONTAINER_NAME="$CONTAINER_NAME" ./deploy.sh
          ENDSSH

      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
