name: Deploy to UBA-PILOT

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Docker image tag to deploy'
        required: true
        default: 'v0.0.0'
      BRANCH:
        description: 'Git branch to deploy'
        required: true
        default: 'main'
  push:
    branches:
      - main

jobs:
  Deploy_on_UBA_PILOT:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: UBA-DEPWD-PILOT

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_PILOT }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME_PILOT }} >> ~/.ssh/known_hosts

      - name: Deploy Stack via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME_PILOT }}@${{ secrets.HOST_NAME_PILOT }} <<'ENDSSH'
          export BASE_DIR="${{ secrets.TARGET_DIR_PILOT }}"
          export BRANCH="${{ github.event.inputs.BRANCH || 'main' }}"
          export TAG="${{ github.event.inputs.TAG || 'latest' }}"
          export REPO_NAME="ubi-wallet-backend"
          export REPO_URL="https://github.com/PSMRI/ubi-wallet-backend.git"
          export CONTAINER_NAME="ubi-wallet-backend"
          
          cd "$BASE_DIR"
          
          # Prepare .env
          if [ -f .env ]; then rm .env; fi
          echo '${{ secrets.DEV_ENV_PILOT }}' > .env
          
          # Run deployment script
          bash deploy.sh
          ENDSSH

      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
