name: Deploy to UBA-DEPWD-PILOT
on:
  workflow_dispatch:
  push:  
    branches:
      - depwd-pilot    
jobs:
  Deploy_on_UBA-DEPWD-PILOT:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: UBA-DEPWD-PILOT
    steps:
      - name: Deploy Stack via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME_PILOT }}
          username: ${{ secrets.USERNAME_PILOT }}
          key: ${{ secrets.EC2_SSH_KEY_PILOT }}
          port: ${{ secrets.PORT_PILOT }}
          script: |    
            cd ${{ secrets.TARGET_DIR_PILOT }}
            if [ -f .env ]; then
              rm .env
            fi
            echo '${{ secrets.DEV_ENV_PILOT }}' > .env
            ls -ltra
            ./deploy.sh

      ## Notify on Slack
      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
